---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx1
spec:
  selector:
    matchLabels:
      app: myapp-nginx1
  template:
    metadata:
      labels:
        app: myapp-nginx1
    spec:
      containers:
        - name: myapp1
          image: cabanitos/mynginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-nginx-service
spec:
  selector:
    app: myapp-nginx1
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31090
